#!/usr/bin/perl

use strict;
use warnings;

use AnyEvent::HTTP;
use Getopt::Long;
use Term::ANSIColor;

sub create_dir_if_exists {
    my $dir = shift;
    my $i = 1;
    while (1) {
        if (!(-e $dir.$i)) {
            system("mkdir ".$dir.$i);
            return $dir.$i;
        }
        $i++;
    }
}

my $CONFIG = {}; 
GetOptions($CONFIG, qw/ 
    url=s
    max-active-downloads=i
    tmp-dir=s
    retries-count=i
    help
/);

if (exists $CONFIG->{help} || not exists $CONFIG->{url}) {
    print "Execute: download_video\n";
    print "\t--url                  - URL for concat 'segment[n].ts' and get full video\n";
    print "\t--max-active-downloads - Maximum active segments downloads, default: 5\n";
    print "\t--tmp-dir              - Temporary directory for save files, default: /tmp\n";
    print "\t--retries-count        - Number of attempts to download one segment (-1 means infinitive), default: 5\n";
    print "\t--help                 - Show this message\n";
    exit;
}

$CONFIG->{'tmp-dir'} ||= "/tmp";
$CONFIG->{'tmp-dir'} = create_dir_if_exists($CONFIG->{'tmp-dir'}.'/tmp');
$CONFIG->{'max-active-downloads'} ||= 5;
$CONFIG->{'retries-count'} ||= 5;

my $url = $CONFIG->{url};
my $stop = 0;
my $dir = create_dir_if_exists($CONFIG->{'tmp-dir'}."/ts");
my $max_active_downloads = $CONFIG->{'max-active-downloads'};
my $current_part = 1;
my $last_part = 0;

$| = 1;

my $cv = AnyEvent->condvar;
my $time_start = 0;

sub download {
    my $number = shift;
    my $attempt = shift;

    if (!$attempt) {
        print color("bold red");
        print "Error: segment$number.ts, can not download this segment :(\n";
        print color('reset');

        if ($current_part + 1 <= $last_part) {
            $current_part++;
            download($current_part, $CONFIG->{'retries-count'});
        }
        return;
    }
    
    $cv->begin;
    http_get(
        "$url/segment$number.ts",
        timeout => 5,
        sub {
            my ($data, $headers) = @_;
            my $response_code = $headers->{Status};
            my $speed = $current_part / (time - $time_start + 1);
            my $await_time = ($last_part - $current_part) / $speed; # in seconds
            $await_time = sprintf("%.1f", $await_time / 60); # in minutes
            print "Process: $current_part / $last_part, await time ~ $await_time minutes            \r"; 
            if ($response_code =~ /^2/) { 
                open (my $fh, ">", "$dir/$number.ts") or die $!;
                syswrite($fh, $data);
                close($fh);
                if ($current_part + 1 <= $last_part) {
                    $current_part++;
                    download($current_part, $CONFIG->{'retries-count'});
                }
            } else {
                print color("bold yellow");
                print "Bad attempt: segment$number.ts, try again";
                print "($attempt / ".$CONFIG->{'retries-count'}.")                \n" if ($attempt != -1);

                print color('reset');
                download($number, ($attempt == -1) ? -1 : $attempt - 1);
            }

            $cv->end;
        }
    );
}

sub is_zero_size {
    my $number = shift;

    my $result = 0;
    my $condvar = AnyEvent->condvar;
    $condvar->begin;

    http_head(
        "$url/segment$number.ts",
        sub {
            my ($data, $headers) = @_;

            if ($headers->{'content-length'} == 0 || $headers->{Status} == 404) {
                $result = 1;
            }

            $condvar->end;
        }
    );

    $condvar->recv;

    return $result
}

sub get_last_segment_number {
    my $current_segment = 1;

    while (not is_zero_size($current_segment)) {
        print "Try get: $current_segment segments\r";
        $current_segment += 100;
    }

    $current_segment -= 100;

    while (not is_zero_size($current_segment)) {
        print "Try get: $current_segment segments\r";
        $current_segment += 10;
    }

    $current_segment -= 10;

    while (not is_zero_size($current_segment)) {
        print "Try get: $current_segment segments\r";
        $current_segment++;
    }

    return $current_segment - 1;
}

print color("bold blue");
print "Try to find last segment...\n";
print color('reset');

$last_part = get_last_segment_number();
print "\n";

print color("bold blue");
print "Start download\n";
print color('reset');

$cv->begin;

$time_start = time;
for my $i (1 .. $max_active_downloads) {
    download($i, $CONFIG->{'retries-count'});
}

$cv->end;
$cv->recv;

print color("bold green");
print "\nEnd download (". (time - $time_start) . "s)\n";
print color('reset');

print color("bold blue");
print "Start concatinate\n";
print color('reset');

my $tmp = $CONFIG->{'tmp-dir'};
my $list_path = "$tmp/list_download_video";

system("rm -rf $list_path");
open(my $fh, ">", $list_path) or die $!;

for my $i (1 .. $last_part) {
    if (-e "$dir/$i.ts") {
        print $fh "file '"."$dir/$i.ts"."'\n";
    }
}
close($fh);

system("rm -rf $tmp/video.ts");
system("ffmpeg -f concat -safe 0 -i $list_path -c copy $tmp/video.ts");
system("rm -rf $tmp/video.mp4");
system("ffmpeg -i $tmp/video.ts -bsf:a aac_adtstoasc -c copy $tmp/video.mp4");

print color("bold green");
print "Success, result placed to: $tmp/video.mp4\n";
print color('reset');

system("open ".$CONFIG->{'tmp-dir'});
